### ISSUE TITLE
Filetype is not required -- better error message, or guess the filetype.

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/biovalidator#24]
I get this error message when I don't provide a filetype:

```
java.lang.IllegalArgumentException: Invalid validator type
	at org.intermine.biovalidator.validator.ValidatorType.of(ValidatorType.java:43)
	at org.intermine.biovalidator.api.ValidatorHelper.validate(ValidatorHelper.java:70)
```

Instead can we do either (if filetype is NULL):

a. guess
b. give an error message "filetype required: FASTA or GFF3"

**Comment by julie-sullivan** [comment]
this is working for fasta and gff.
